backend:
  name: git-gateway
  branch: netlify-cms
media_folder: "content/images"
public_folder: "/static"
collections:
  - name: "page"
    label: "Page"
    folder: "content/pages"
    extension: "mdx"
    format: "frontmatter"
    nested:
      depth: 100
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Display Order", name: "display order", widget: "number", value_type: "int", min: 0, default: 0}
      - {label: "Body", name: "body", widget: "markdown"}